= micro-javaee

This project compares different deployment configurations of JavaEE micro-service.

== Prerequesites

* JDK 8
* Maven 3

== WAR deployment

The application is packaged as a war.

[source]
----
mvn wildfly:run
----

Wildfly distribution is downloaded and unzipped in target directory.
The application is packaged as a war and deploy to Wildfly.

== Wildfly Swarm

More information : http://wildfly.org/swarm/

[source]
----
mvn clean package -Pswarm
----

The application is packaged as a `fat` jar with a some wildfly modules embedded : `micro-javaee-swarm.jar`.

You can start the application with :

[source]
----
java -jar target/micro-javaee-swarm.jar
----

== Payara Micro

More information : http://www.payara.co.uk/introducing_payara_micro

[source]
----
mvn clean package -Ppayara
----

The application is packaged as a war. Payara micro is downloaded and put in target directory.

You can start the application with Payara micro as bootstrap :

[source]
----
java -jar target/payara-micro.jar --deploy target/micro-javaee.war
----

== TomEE Embedded

More information : https://rmannibucau.wordpress.com/2014/03/24/java-jar-my-app-in-tomee-jar/

[source]
----
mvn clean package tomee:exec -Ptomee
----

The application is packaged as an executable jar. At startup, TomEE is unpacked just near the jar.

You can start the application with :

[source]
----
java -jar target/micro-javaee-exec.jar
----

== KumuluzEE

More information : https://ee.kumuluz.com/

[source]
----
mvn clean package -Pkumuluzee
----

The dependencies are copied into target/dependency.

You can start the application with :

[source]
----
CONTEXT_PATH=/micro-javaee java -cp target/classes:target/dependency/* com.kumuluz.ee.EeApplication
----

== Comparison

[format="csv", options="header"]
|===
,Wildfly,Swarm,Payara Micro,TomEE Embedded, KumuluzEE
Packaging, war + application server, jar, war + jar, jar, classes + target/dependency/
Size, 10 Ko + 159 Mo, 83 Mo, 10 Ko + 57 Mo, 44 Mo, 15 Mo
Startup time,7s,4s,9s,2s,1s
|===
